print('What do you get when you cross a snowman with a vampire?\nFrostbite!')
input()
print('What do dentists call a astronaut\'s cavity?')
print('A black hole!')
print()
print('Knock knock.')
print("Who's there?")
print('Interrupting cow.')
print('Interrupting cow wh', end='')
print('-MOO!')
print()
print('What do you get when you cross a ghost with a cat?')
print ("\"A scaredy cat!\"")
print()
print('What do you get when you cross a karate expert and a pig?')
print('A porkshop!'.lower())
print()
print("Hi what's your name?")
myName=input()
print(myName+ ' do you want to be best friends?')
print('Look up at the stars, thats how much I want to be your friend.')
print('But it\'s morning, there aren\'t any stars?')
print('Exactly!'.upper())

